//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCardsData
    {
        public int imgCardID { get; set; }
        public Nullable<int> CollegeID { get; set; }
        public byte[] FrontPicture { get; set; }
        public byte[] BackPicture { get; set; }
        public Nullable<int> ClassID { get; set; }
        public byte[] Signature { get; set; }
        public string PrintReportName { get; set; }
        public byte[] SampleCard { get; set; }
    
        public virtual tblCardsData tblCardsData1 { get; set; }
        public virtual tblCardsData tblCardsData2 { get; set; }
        public virtual tblCollege tblCollege { get; set; }
    }
}
