//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClass()
        {
            this.tblStudents = new HashSet<tblStudent>();
        }
    
        public int ClassID { get; set; }
        public Nullable<int> CollegeID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> SubjectGroupID { get; set; }
        public Nullable<int> YearID { get; set; }
        public string ValidUpto { get; set; }
    
        public virtual tblCollege tblCollege { get; set; }
        public virtual tblSession tblSession { get; set; }
        public virtual tblSubjectGroup tblSubjectGroup { get; set; }
        public virtual tblYear tblYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudent> tblStudents { get; set; }
    }
}
