//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPicture
    {
        public int ImgID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
    }
}
