//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStudent
    {
        public int StudentID { get; set; }
        public string RegisterationNumber { get; set; }
        public string RollNumber { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string FormNumber { get; set; }
        public byte[] Picture { get; set; }
        public string FatherName { get; set; }
        public string SubjectGroupName { get; set; }
        public string ClassName { get; set; }
        public string SessionName { get; set; }
        public string YearName { get; set; }
        public string CollegeName { get; set; }
        public string CollegeAddress { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> CollegeID { get; set; }
        public string ValidUpto { get; set; }
        public int SessionID { get; set; }
        public int YearID { get; set; }
        public int SubjectGroupID { get; set; }
        public int ImgID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Subject { get; set; }
    }
}
